// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: P4_BOX_SR

#include "../ui.h"

void ui_ScreenSR_screen_init(void)
{
    ui_ScreenSR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DropdownTip = lv_dropdown_create(ui_ScreenSR);
    lv_dropdown_set_options(ui_DropdownTip,
                            "测试词语列表\n打开电灯\n关闭电灯\n打开空调\n关闭空调\n送风模式\n开启制热\n开启通风\n均匀风\n有点冷\n有点热\n电辅热\n自动");
    lv_dropdown_set_selected_highlight(ui_DropdownTip, false);
    lv_obj_set_width(ui_DropdownTip, 354);
    lv_obj_set_height(ui_DropdownTip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownTip, 1);
    lv_obj_set_y(ui_DropdownTip, -143);
    lv_obj_set_align(ui_DropdownTip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownTip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_DropdownTip, &ui_font_FontSR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_DropdownTip, &ui_font_FontSR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownTip), &ui_font_FontSR,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownTip), &ui_font_FontSR,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_LabelSR = lv_label_create(ui_ScreenSR);
    lv_obj_set_width(ui_LabelSR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSR, -10);
    lv_obj_set_y(ui_LabelSR, 0);
    lv_obj_set_align(ui_LabelSR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSR, "开始测试");
    lv_obj_set_style_text_font(ui_LabelSR, &ui_font_FontSR36, LV_PART_MAIN | LV_STATE_DEFAULT);

}
