// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: P4_BOX_SR

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenSR
void ui_ScreenSR_screen_init(void);
lv_obj_t * ui_ScreenSR;
lv_obj_t * ui_DropdownTip;
lv_obj_t * ui_LabelSR;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1536001197[1] = {&ui_img_1924961647};
const lv_img_dsc_t * ui_imgset_727336564[1] = {&ui_img_1545807356};
const lv_img_dsc_t * ui_imgset_1308077219[1] = {&ui_img_1126967247};
const lv_img_dsc_t * ui_imgset_2125324509[3] = {&ui_img_1706561437, &ui_img_424947501, &ui_img_1184979050};
const lv_img_dsc_t * ui_imgset_coffee_pic_[1] = {&ui_img_coffee_pic_2_png};
const lv_img_dsc_t * ui_imgset_702871297[1] = {&ui_img_374834912};
const lv_img_dsc_t * ui_imgset_592227649[1] = {&ui_img_1283678341};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenSR_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenSR);
}
