// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: P4_BOX_SR

#ifndef _P4_BOX_SR_UI_H
#define _P4_BOX_SR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenSR
void ui_ScreenSR_screen_init(void);
extern lv_obj_t * ui_ScreenSR;
extern lv_obj_t * ui_DropdownTip;
extern lv_obj_t * ui_LabelSR;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1924961647);    // assets/coffee-1839734_1280.png
LV_IMG_DECLARE(ui_img_1545807356);    // assets/coffee-1974841_1280.png
LV_IMG_DECLARE(ui_img_1126967247);    // assets/coffee-cup-2317201_1280.png
LV_IMG_DECLARE(ui_img_1706561437);    // assets/coffee-pic1.png
LV_IMG_DECLARE(ui_img_424947501);    // assets/coffee-pic3.png
LV_IMG_DECLARE(ui_img_1184979050);    // assets/coffee-pic4.png
LV_IMG_DECLARE(ui_img_coffee_pic_2_png);    // assets/coffee_pic_2.png
LV_IMG_DECLARE(ui_img_374834912);    // assets/drink-pic4.png
LV_IMG_DECLARE(ui_img_1283678341);    // assets/neon-sign-4343663_1280.png


LV_FONT_DECLARE(ui_font_FontPromt);
LV_FONT_DECLARE(ui_font_FontSR);
LV_FONT_DECLARE(ui_font_FontSR36);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
